import { Article } from './article';

export const ARTICLES: Article[] = [
    {
        id: 1,
        title:  "免费模式经典操作之“加倍返钱”解密",
        type: 0,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/weapp1/pic/120/7075_1578468441641_86.jpg",
        author: "张天一",
        date: 1568260666,
        desc: "“加倍返钱”是壹玖免费模式中经常用到的非常具有杀伤力的商业设计，那么什么是加倍返钱模式?假设你的A产品原价销售，全额返还B产品无门槛消费金额，相当于一次钱当两次花，达到加倍返还效果，这就是加倍返钱模式。",
        content:'<h1><img src="http://uqun.oss-cn-hangzhou.aliyuncs.com/files/pic/1907/hna6d5t74f.jpg" style="color: rgb(51, 51, 51); font-size: 14px;max-width:100%"><strong style="color: rgb(0, 0, 0);">免费模式经典操作之“加倍返钱”解密</strong></h1><div><strong style="color: rgb(0, 0, 0);">2019-07-16 壹玖生态大系统文创部</strong></div><p line="9c8d"><strong style="color: rgb(77, 128, 191);">“免费模式是一种利他、吃亏的思维方式，把这种思维方式植入企业运营的过程中，来换取其他点的合作机会，并创造利润”。</strong></p><p line="5a12"><strong style="color: rgb(77, 128, 191);">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ——袁国顺</strong></p><p><span>&nbsp; &nbsp;</span><img src="http://uqun.oss-cn-hangzhou.aliyuncs.com/files/pic/1907/y3f6v85ksw.png">&nbsp; &nbsp;&nbsp;</p><p line="f9f5" linespacing="131"><strong style=""><span style="font-size: medium;">&nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-size: large;"> “加倍返钱”</span></strong><span style="font-size: medium;">是壹玖免费模式中经常用到的非常具有杀伤力的商业设计，那么什么是加倍返钱模式?假设你的A产品原价销售，全额返还B产品无门槛消费金额，相当于</span><strong style="font-size: medium;">一次钱当两次花，达到加倍返还效果，这就是加倍返钱模式。</strong></p><p line="9f98" linespacing="131"><span style="font-size: x-large;">用方案讲解：&nbsp;</span></p><p line="6096" linespacing="131"><span style="font-size: medium;">1、200元购买孕妇装，返200元在卡内，等宝宝出生后，今后可以购买宝宝用品;&nbsp;</span></p><p line="c2be" linespacing="131"><span style="font-size: medium;"><span>2、如果今后他来购买宝宝用品花完了卡里的钱，你再送他一张200元的返钱卡，你说，只要购满2000元，这个200元的卡又可以激活领现金了!</span><span>&nbsp;</span></span></p><p line="6abe" linespacing="131"><span style="font-size: medium;">如此一来，又形成了一个连环锁!</span></p><p><span>&nbsp; &nbsp;&nbsp;</span><img src="http://uqun.oss-cn-hangzhou.aliyuncs.com/files/pic/1907/wckfrtdwmt.png">&nbsp; &nbsp;</p><p line="6d0b" linespacing="131"><span style="font-size: medium;"><span>&nbsp; &nbsp; &nbsp; &nbsp; 这里的话，其实</span><strong>孕妇装它就相当于是个引流产品</strong><span>，现在如果说你要购买孕妇装的话，一个是两百块钱什么都没有，另外一个是返还两百块钱，你会选择哪个？</span></span></p><p line="4e48" linespacing="131"><span style="font-size: medium;"><span>&nbsp; &nbsp; &nbsp; &nbsp;其实呢，这就是一个巧妙的引流和后端锁定消费的策略，比如说孕妇装的成本是八十块钱，那么其实</span><strong>相当于八十块钱的成本锁定了一个后端消费的准客户。</strong></span></p><p line="7619" linespacing="131"><span style="font-size: medium;"><span>&nbsp; &nbsp; &nbsp; &nbsp; 并且呢，在这个宝宝还没有出生之前现金流是在你手上的，当下，你是赚钱的，你</span><strong>相当于用未来付出的引流成本锁定了精准顾客。</strong></span></p><p line="7421" linespacing="131"><span style="font-size: medium;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;为了让你更进一步理解这个模式的操作，我们再举例说明：&nbsp;</span></p><p><span>&nbsp; &nbsp;</span><img src="http://uqun.oss-cn-hangzhou.aliyuncs.com/files/pic/1907/cfia2r6wbt.png">&nbsp; &nbsp;&nbsp;</p><p line="5966" linespacing="131"><span style="font-weight: bold;">1、原价118元的老年人自动调焦眼镜，现在只要48元;</span></p><p line="f5ef" linespacing="131"><span style="font-weight: bold;">2、现在购买还送50元鸡蛋消费卡;</span></p><p line="2780" linespacing="131">&nbsp; &nbsp; &nbsp; &nbsp; <span style="font-size: medium;">原价一百一十八元的老年人自动调焦眼镜，现在只要四十八块钱。并且你现在购买后送你五十块钱的鸡蛋消费卷，你可以去找我们指定的地方买鸡蛋，这是</span><span style="font-size: x-large;"><span style="font-weight: bold;">“</span><strong style="">买虚送实”</strong></span><span style="font-size: medium;">的做法。</span></p><p line="fb18" linespacing="131"><span style="font-size: medium;">&nbsp; &nbsp; &nbsp; &nbsp; 那么这样的话，你就透过前面的这个产品作为切入点，能够获得很多中老年的关注。甚至个别的中年人除了给自己父母买这种自动调焦眼镜以外，他也会买一副，目的不是眼睛，而是拿着这个卡去买鸡蛋。</span></p><p><span>&nbsp; &nbsp;</span><img src="http://uqun.oss-cn-hangzhou.aliyuncs.com/files/pic/1907/6h8dpvdtku.png">&nbsp; &nbsp;&nbsp;</p><p line="2609" linespacing="131"><span style="font-size: medium;"><span>&nbsp; &nbsp; &nbsp; &nbsp; 因为鸡蛋对他来说，是生活刚需，总要买的。这样你就能够激活很多原本不需要眼镜的人的购买需求，其实相当于关联到你后面的这个鸡蛋消费里面来了。</span><span>&nbsp;</span></span></p><p line="5fbe" linespacing="131"><span style="font-size: medium;"><span>&nbsp; &nbsp; &nbsp; &nbsp; 那么这个自动调焦眼镜成本其实只要10块钱一副，价值感是不错的，通过</span><strong>买虚送实</strong><span>的形式吸引大量人手上握有你指定店铺的这个鸡蛋消费卡。&nbsp;</span></span></p><p line="fb88" linespacing="131"><span style="font-size: medium;">3、消费鸡蛋的时候，再送50元返钱券，告诉对方，只要今后购买满350元土鸡，这50元即可激活领现金!&nbsp;</span></p><p line="f070" linespacing="131"><span style="font-size: medium;"><strong>&nbsp; &nbsp; &nbsp; &nbsp; 透过自动调焦眼镜，然后送鸡蛋把它关联到你的指定的消费的场所，同时在透过他来领鸡蛋的时候，他把鸡蛋消费完之后，然后你再用五十元消费满多少可以激活现金的形式，又锁定了你后端卖鸡的项目。</strong><span>&nbsp;</span></span></p><p line="cec3" linespacing="131"><span style="font-size: medium;"><span>&nbsp; &nbsp; &nbsp; &nbsp; 到最后，身份揭密，其实你就是一个农场里面卖鸡蛋和鸡的，你是做农场的，你本来你就是卖鸡蛋和鸡的，通过这种方式你可以在前端打通很多精准客户，你可以在前端抓到很多的数据。而且可以去放大，</span><strong>这个操作思路，这就是一个连环的一种运作模式。</strong><span>&nbsp;</span></span></p><p line="1e22" linespacing="131"><span style="font-size: medium;"><span>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;大家发现没有，其实你卖任何产品：比如你卖鸡蛋卖鸡，你不一定以你的鸡蛋作为切入点，你</span><strong>在你的主营产品前面可以切入一个虚的东西以虚送实的形式，</strong><span>关联到你的主营产品里面来，这样的话，你才能够有无限量的去想象空间，否则你只有你的主营产品，你的操作永远都会受局限。</span><span>&nbsp;</span></span></p><p line="9f41" linespacing="131"><span style="font-size: medium;">&nbsp; &nbsp; &nbsp; &nbsp; 讲的只是举例，可以依照实际情况调节金额以及增设各种各样的切入产品进行测试，找到最适合的解决方案。</span></p><p line="f60b" linespacing="135"><strong style="font-size: medium;">【请注意】</strong></p><p line="f71b" linespacing="135"><span style="font-size: medium;">&nbsp; &nbsp; &nbsp; &nbsp;<span style="color: rgb(194, 79, 74);"> <span style="font-weight: bold;">警告各位，不懂壹玖《免费模式》的真谛，千万不要轻易去尝试，一定要在老师指导下，完善方案才可以！你需要系统，需要壹玖大系统，只靠你一个人，去实施方案是有很大风险的，没有一个闭环甚至是连环闭环的方案，你是无法达到用后端的利润弥补前段让利的空缺的，将会带来灾难性后果，壹玖免费模式，并不是在鼓吹大家盲从，而是真正的帮助中小微企业，降低风险，扩大收益。思维模式说的简单，但是背后要做的，要依靠的力量是很多的。</span></span></span></p><p><span>&nbsp;&nbsp;</span><img style="max-width:100%" src="http://uqun.oss-cn-hangzhou.aliyuncs.com/files/pic/1907/brukjkd2gs.png">&nbsp; &nbsp; &nbsp;</p><p line="b6a4" linespacing="135"><strong>总结：</strong><span>互联网时代，眼球就是经济，只有持续不断地创新、为顾客创造新鲜感，才能赢得顾客的心。引流是手段，截留是目的，回流是增加客户粘性。</span></p><p></p><p line="Kqok" linespacing="135"><span>100%返款甚至加倍返款，是具有杀伤力的壹玖免费模式应用，试想一下，如果你的产品买1000送1000，甚至买1000送2000，那对市场会有多么大的冲击力！学习壹玖免费模式，学的就是让客户无法拒绝的模式，学的就是让企业化腐朽为神奇的模式，加入壹玖吧，期待与您相逢！</span></p><p line="Kqok" linespacing="135"><span><br></span></p><p line="Kqok" linespacing="135">（注：文中图片部分引自网络，如有侵权，请第一时间联系删除。）&nbsp;&nbsp;<span><br></span></p>',
        positionCon: '',
    },
    {
        id: 2,
        title:  "免费模式设计七步法——袁老师公开课第二讲",
        type: 0,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/weapp1/pic/130/11_1575422573949_91.jpg",
        author: "袁国顺",
        date: 1570762062,
        desc: "排兵布阵→勘察地形→知己知彼→找准靶心→师出有名→稀缺理论→声动击西。",
        content: '',
        positionCon: '',
    },
    {
        id: 3,
        title:  "充30万得30万送40万路虎，还能包你年赚50万",
        type: 1,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/weapp1/pic/120/9698_1578821568443_87.jpg",
        author: "裴呦呦",
        date: 1563359400,
        desc: "充值30万，送40万路虎，再保证年赚50年，这家红酒企业第一天充值25个，收款750万，三天总共充值58个，最终收款1740万。",
        content: '',
        positionCon: '',
    },
    {
        id: 4,
        title:  "超市3天收款270万案例",
        type: 2,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/userupload/1908/1000001492_4pK2ETfXGP.png",
        author: "林天诺",
        date: 1564016991,
        desc: "一家超市交1880元，送1980元电动车，再送199元电饭锅，再退1880元，3天收款270万！锁定周边2000客户！",
        content: '',
        positionCon: '',
    },
    {
        id: 5,
        title:  "5000元婚纱摄影免费拍，8个月成功收款597万！",
        type: 1,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/userupload/1907/1000000152_R8D5KSQtx7.jpg",
        author: "晓庆",
        date: 1563952146,
        desc: "一家婚纱摄影店，5000元婚纱摄影送5000元的礼品，8个月活动期收款597万！成就壹玖免费模式经典案例。",
        content: '',
        positionCon: '',
    },
    {
        id: 6,
        title:  "免费模式之资本分拆手法",
        type: 0,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/userupload/1908/1000001492_nQaNfrRMrG.jpg",
        author: "肯尼迪",
        date: 1564990384,
        desc: "在免费模式免费方案设计中，运用到很多手法，其中有一条就是资本分拆手法，资本分拆又有五种分拆手法，融会贯通才能够将免费模式方案设计的更加圆满，今天带给大家免费模式之资本分拆手法，请细细体会。",      
        content: '',
        positionCon: '',
    },
    {
        id: 7,
        title:  "充卡模型在餐饮行业的应用剖析",
        type: 3,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/userupload/1908/1000001492_xW2ZkAiC5N.jpeg",
        author: "青贮",
        date: 1564996579,
        desc: "相信很多老板都搞过充值活动，尤其是餐饮行业，各种各样的充值不断，花样也是层出不穷，但是结果只有一个——消费者蒙圈了，不知道该选择谁，充值结果也就不尽人意了。但是，充值确实是一个好方法，袁老师在曾经说过，“交钱才能交心”，钱在哪里，人才能在哪里。",
        content: '',
        positionCon: '',
    },
    {
        id:8 ,
        title:  "火锅免费吃，充卡就送车，这家老板疯了吧",
        type: 2,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/userupload/1908/1000001492_6dRShxhQEX.jpeg",
        author: "锦衣夜行",
        date: 1564997700,
        desc: "免费模式不是不要钱，而是一种吃亏、利他的思维方式，把这种思维方式运营到企业的经营活动中，已达成更多领域的合作，延长利润链条，赚客户看不到的钱，从而完成利润目标。",
        content: '',
        positionCon: '',
    },
    {
        id:9,
        title:  "汽车美容店客流引秘籍",
        type: 3,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/userupload/1908/1000001492_rQ4TJ5Y6Pw.jpeg",
        author: "花花",
        date: 1564998633,
        desc: "以前有一位汽车美容店的老板经朋友介绍找到我，向我咨询如何告别坐等生意的窘境，做到主动开发客户。",
        content: '',
        positionCon: '',
    },
    {
        id:10,
        title:  "山东大汉卖红枣的营销案例",
        type: 2,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/userupload/1908/1000001492_rNwwNrhSK5.png",
        author: "顾城",
        date: 1565002310,
        desc: "一个卖枣的山东大汉，在那里大叫，山东大枣又大有甜，十块钱两袋，大家过来看看等这样的话语，说了老半天但并没有多少人问津，满满的一箱子并没怎么销售出去，看着他皱着眉头，心里一定在思考着问题，是地方选错了还是什么问题？",
        content: '',
        positionCon: '',
    },
    {
        id:11,
        title:  "餐厅酒水饮料全免费，看免费模式如何破局？",
        type: 1,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/userupload/1908/1000001492_3PJkAy7wrm.png",
        author: "潇潇",
        date: 1565008632,
        desc: "作为一个餐饮行业的经营者，除了思考靠菜品酒水差价赚钱以外还能思考什么？菜品不赚钱，靠卖时间赚钱；又或者是靠广告，或者是其他的等等。",
        content: '',
        positionCon: '',
    },
    {
        id:12,
        title:  "洗车行亏损到年赚5000万",
        type: 0,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/userupload/1908/1000001492_RzHKXtyRKc.jpg",
        author: "一菲",
        date: 1565061923,
        desc: "洗车行如何用免费模式从年亏50万到年赚5000万？",
        content: '',
        positionCon: '',
    },
    {
        id:13,
        title:  "一家商店经营11年，年利润400万",
        type: 3,
        img: "http://uqun.oss-cn-hangzhou.aliyuncs.com/userupload/1908/1000001492_hriMsjZPFw.jpg",
        author: "燕子",
        date: 1565062712,
        desc: "一家不要钱的商店，却经营了11年，年利润400万？",
        content: '',
        positionCon: '',
    },
]